### ISSUE TITLE
Add relation for subject_group, bg:isSubjectGroup to allow annotation of patient/control groups

### ISSUE THREAD

**Issue by alyssadai** [neurobagel/bagelbids#26]
The API query route currently depends on an `isSubjectGroup` relation to filter for healthy controls or patients only, but this does not exist in the graph/datamodel yet (and so any related queries will return empty lists for now).

`isSubjectGroup` should be added to the graph with at least one value for healthy controls, http://purl.obolibrary.org/obo/NCIT_C94342.

Ideally, it could also have a value for patients (from NCIT, http://purl.obolibrary.org/obo/NCIT_C16960 (Patient) or http://purl.obolibrary.org/obo/NCIT_C70668 (Clinical study subject) are options) and one for general study subjects, for datasets where subjects don't have a diagnosis but aren't necessarily all "healthy controls" (or maybe this info is missing somehow).

**Comment by surchs** [comment]
Closed by #61
