### ISSUE TITLE
can serialize a complete graph model

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelbids#34]
- [x] go line by line through the tsv
  - [x] create instances of subjects ~~and sessions~~ edit: we will add sessions to the graph when we model phenotypic variables at the session level
  - [x] combine into a nb:Dataset instance
  - [x] give the dataset a name. needs to be user specified.
  - [x] serialize to json

**Comment by surchs** [comment]
We currently have two conflicting goals:

1. For the current release we plan to still store phenotypic metadata at the level of the subject
2. We have also decided to handle session information in the `bagel pheno` command

Typically session information is only available if there is more than one session. If that is the case, we would have to pick one session and apply the associated phenotypic information to the subject. Not ideal, but probably still useful. I'm leaning towards this solution.

The alternative would be that we need to update the API to expect these metadata to be attached to the session instance from now on. @alyssadai: do you have a sense of how much work that would be? I know we had said we'd tackle that in a future release.

**Comment by surchs** [comment]
Another note here: because the `bagel pheno` subcommand only expects a `participants.tsv` and a `participants.json`, we need to ask the user to provide the name of the dataset manually. If this were a BIDS directory, we could read the dataset name from the `dataset_description.json` file. But we can't expect this file to exist. We can also not expect the filename itself to reflect the dataset name (because if the files come from a BIDS dataset, their filenames would be generic). 

So a mandatory user supplied option for dataset name seems to be the only option here. On the plus side: we can use that as a sanity check when `bagel bids` gets implemented to check that we are merging data for the same dataset.

**Comment by alyssadai** [comment]
@surchs in terms of the API expecting the metadata to be attached to the session instance, off the top of my head I think this would mainly entail rewriting the [create_query](https://github.com/neurobagel/api/blob/main/app/api/utility.py#L41) function in utility.py, which shouldn't be too big of a challenge. That being said, would we expect phenotypic metadata (age, sex, etc.) to change from session to session? If I remember correctly our group decision to keep it at the subject level was because a reasonable assumption is "no", in which case your proposal of
> pick one session and apply the associated phenotypic information to the subject  

would make sense in the vast majority of cases, I think.

**Comment by surchs** [comment]
> shouldn't be too big of a challenge

Thanks, that's what I thought as well. We'll still tackle it in a second round I'd say.

>  would we expect phenotypic metadata (age, sex, etc.) to change from session to session

Yes, that is indeed the reason. What reasonably changes and how often will obviously vary between variables, but age and the available assessment tools changing would be expected. We'll think it through more closely when we implement this.

**Comment by alyssadai** [comment]
Sounds good. Good point about the age + assessment tools, I forgot that with longitudinal data age is collected multiple times. 🤦‍♀️
