### ISSUE TITLE
Generate example jsonld output for our test data 

### ISSUE THREAD

**Issue by surchs** [neurobagel/bagelbids#39]
- [x] matches one example of .tsv and .jsonld input - and that's tested
- [x] covers all pheno attributes (where possible - dx vs control)
- [x] matches one of the BIDS examples, ideally synthetic

**Comment by surchs** [comment]
@alyssadai anything else you can think of for the jsonld example?

**Comment by alyssadai** [comment]
Nope, think this looks good!
